### PR TITLE
Release version 0.8.2

### PR DESCRIPTION
**Pull request by dd32**
Some issues have been identified since 0.8 + 0.8.1 was released, 0.9.0 is a little ways off still so let's release 0.8.2 to resolve those issues for now:

 - #558 
 - #557
 - #559
 - #552
   - Not an issue, but should be bumped on WordPress.org)
 - #578

## Release instructions

- [x] Branch: Starting from `tags/0.8.1`, create a branch named `release/0.8.2` for the release-related changes.
- [x] Version bump: Bump the version number in `readme.txt` and `two-factor.php` if it does not already reflect the version being released.  Update both the plugin "Version:" header value and the plugin `TWO_FACTOR_VERSION` constant in `two-factor.php`.
- [ ] ~~Changelog: Add/update the changelog in `readme.txt`.~~
- [ ] ~~New files: Check to be sure any new files/paths that are unnecessary in the production version are included in [.distignore](https://github.com/WordPress/two-factor/blob/master/.distignore).~~
- [x] Readme updates: Make any other readme changes as necessary. `readme.md` is geared toward GitHub and `readme.txt` contains WordPress.org-specific content. The two are slightly different.
- [x] Create Release PR: Push any local changes in `release/0.8.2` to origin, create a release PR, and request review to ensure all CI checks pass and ensure master branch changes are limited to merges only.
- [ ] ~~Merge: After review approval, merge the release pull request (or make a non-fast-forward merge from your release branch to `master`).  `master` contains the latest stable release.~~
- [x] Release: Create a [new release](https://github.com/WordPress/two-factor/releases/new), naming the tag and the release with the new version number, and targeting the `release/0.8.2` branch.  ~~Paste the changelog from `readme.txt` into the body of the release and include a link to the [closed items on the milestone](https://github.com/WordPress/two-factor/milestone/23?closed=1).~~
- [x] SVN: Wait for the [GitHub Action: Deploy](https://github.com/WordPress/two-factor/actions/workflows/deploy.yml) to finish deploying to the WordPress.org repository.  If all goes well, users with SVN commit access for that plugin will receive an emailed diff of changes.
- [x] Check WordPress.org: Ensure that the changes are live on https://wordpress.org/plugins/two-factor/. This may take a few minutes.
- [ ] ~~Mark any included PRs / Issues as 0.8.2 from 0.9.0 if appropriate~~
- [ ] Close the milestone: Edit the [milestone](https://github.com/WordPress/two-factor/milestone/27) with the release date (in the `Due date (optional)` field) and link to the GitHub release (in the `Description` field), then close the milestone.
- [x] ~~Punt incomplete items: If any open issues or PRs which were milestoned for `0.8.2` do not make it into the release, update their milestone to `0.9.0` or `Future Release`.`~~
- [x] Cherry pick the version bump commit to `master` -- #588

### CODE REVIEW

**Review by jeffpaul — APPROVED** [review]
Given the 👍🏼 on https://github.com/WordPress/two-factor/pull/570#issuecomment-1561249623, I'm going to approve this as good... thanks for handling the release @dd32!

**Comment by iandunn** [comment]
Should we include #575 here too @dd32 ?

**Comment by iandunn** [comment]
Er, nevermind, it looks like #529 isn't slated until `0.9.0`, so #575 doesn't apply 👍🏻

**Comment by shaunek-hero** [comment]
Hi I'm just and observer and a happy user of this fine plugin, but wondering when this 0.8.2 might be approved and released? I've had some complaints about #557 and I have applied the appropriate fix on my own WP instances but would would love to see this release out, assuming it is ready to go.

**Comment by iandunn** [comment]
This has been released now:

* https://github.com/WordPress/two-factor/releases/tag/0.8.2
* https://wordpress.org/plugins/two-factor/

Closing this PR since this isn't intended to be merged to the main branch.

**Pull request closed without merging**
