### PR TITLE
login_site_html_link hook fix

### PR DESCRIPTION
**Pull request by pepijnnichting**
Use the login_site_html_link hook just like in wp-login.php

### CODE REVIEW

**Comment by kasparsd** [comment]
@pepijnnichting I wonder if we could replace the whole footer section with a call to `login_footer()` just like WP core does it here:

https://github.com/WordPress/WordPress/blob/c6028577a462f235da67e5d3dcf1dc42f9a96669/wp-login.php#L1446

and leave just our custom styles above that call.

**Comment by pepijnnichting** [comment]
I did a quick check and this seems to work! This looks like a much better solution.

**Comment by kasparsd** [comment]
Thanks @pepijnnichting! I wonder why it wasn't using this before? Were you able to test the whole login flow with this update?

**Comment by pepijnnichting** [comment]
@kasparsd Tested the flow for email, dummy and totp as provider and all work. I dit not check fido and backup-codes.

**Pull request merged**
