### PR TITLE
Release plugin version 0.7.3

### PR DESCRIPTION
**Pull request by kasparsd**
Covers https://github.com/WordPress/two-factor/compare/0.7.2...79c364169e4e7fc430c4ed05c9cc81402955785c

- https://github.com/WordPress/two-factor/pull/478
- https://github.com/WordPress/two-factor/pull/458 (security improvement)
- https://github.com/WordPress/two-factor/pull/428
- https://github.com/WordPress/two-factor/pull/465
- https://github.com/WordPress/two-factor/pull/466
- https://github.com/WordPress/two-factor/pull/387
- https://github.com/WordPress/two-factor/pull/420

## Changelog

Includes the following changes https://github.com/WordPress/two-factor/compare/0.7.2...79c364169e4e7fc430c4ed05c9cc81402955785c

- Make `wp_login_failed` action call compatible with the WP core argument count and types. Reported in [#471](https://github.com/WordPress/two-factor/issues/471) by @dziudek and fixed in [#478](https://github.com/WordPress/two-factor/pull/478) by @dd32.
- Use `hash_equals()` for nonce comparison to improve security. Reported in [#458](https://github.com/WordPress/two-factor/pull/458) and fixed in [#458](https://github.com/WordPress/two-factor/pull/458) by @calvinalkan.
- Improve compatibility with PHP 8.1 by replacing all instances of `FILTER_SANITIZE_STRING` usage. Reported and fixed in [#428](https://github.com/WordPress/two-factor/pull/428) by @sjinks. 
- Add automated checks for PHP 8 compatibility in [#465](https://github.com/WordPress/two-factor/pull/465) and [#466](https://github.com/WordPress/two-factor/pull/466) by @kasparsd.
- Improve accessibility of two-factor settings in the user profile by introducing a label that links the method names with the associated checkboxes. Reported and fixed in [#387](https://github.com/WordPress/two-factor/pull/387) by @r-a-y.
- Improve TOTP autocomplete behaviour by setting the `autocomplete` attribute [to `one-time-code`](https://web.dev/sms-otp-form/). Reported and fixed in [#420](https://github.com/WordPress/two-factor/pull/420) by @squaredpx.

### CODE REVIEW

**Comment by kasparsd** [comment]
@iandunn, @jeffpaul Technically these are all minor changes that are backwards compatible. Are we OK with pushing them out as a patch release instead of a minor 1.8.0 release?

**Comment by iandunn** [comment]
Yeah, a patch release sounds like a good idea to me 👍🏻

**Comment by jeffpaul** [comment]
@kasparsd looks like this would also include:
* https://github.com/WordPress/two-factor/pull/420

https://github.com/WordPress/two-factor/pull/438 && https://github.com/WordPress/two-factor/pull/470 are effectively on hold, but may be worth re-enabling to see if the 0.7.3 release runs smoothly (or at least provides some error messages I can help triage in hopes of getting this to work for 0.8.0)?

**Comment by kasparsd** [comment]
Totally missed that, thank you @jeffpaul!

**Pull request merged**
