### PR TITLE
Release 0.10.0

### PR DESCRIPTION
**Pull request by kasparsd**
Push out all the minor improvements before a major release.

## What's Changed
* Rely on just-in-time translation loading by @swissspidy in https://github.com/WordPress/two-factor/pull/608
* Update/headers by @jeffpaul in https://github.com/WordPress/two-factor/pull/610
* Update short description by @jeffpaul in https://github.com/WordPress/two-factor/pull/612
* Fix typos by @szepeviktor in https://github.com/WordPress/two-factor/pull/617
* Bump tested upto version to WP 6.6 by @mehul0810 in https://github.com/WordPress/two-factor/pull/616
* Fire an action when a user revalites their 2FA session. by @dd32 in https://github.com/WordPress/two-factor/pull/620
* Bump minimum WP to 6.3, minimum PHP to 7.2. by @dd32 in https://github.com/WordPress/two-factor/pull/625
* Remove old grunt deploy related code. See #543 by @dd32 in https://github.com/WordPress/two-factor/pull/627
* Fix Action unit testing by @dd32 in https://github.com/WordPress/two-factor/pull/624
* Bump axios from 1.6.8 to 1.7.4 by @dependabot in https://github.com/WordPress/two-factor/pull/626
* Bump braces from 3.0.2 to 3.0.3 by @dependabot in https://github.com/WordPress/two-factor/pull/613
* Bump webpack from 5.91.0 to 5.94.0 by @dependabot in https://github.com/WordPress/two-factor/pull/628
* Update two factor options layout by @thrijith in https://github.com/WordPress/two-factor/pull/623
* Bump send and express by @dependabot in https://github.com/WordPress/two-factor/pull/634
* Accessibility for options page by @dd32 in https://github.com/WordPress/two-factor/pull/632
* Fix errors reported by PHPStan by @szepeviktor in https://github.com/WordPress/two-factor/pull/619
* Fix failing unit test by @kasparsd in https://github.com/WordPress/two-factor/pull/639
* Add basic PHPStan linter by @kasparsd in https://github.com/WordPress/two-factor/pull/638
* Update screenshots to match the current UI by @kasparsd in https://github.com/WordPress/two-factor/pull/636
* Improve discoverability by @kasparsd in https://github.com/WordPress/two-factor/pull/635
* Delete user meta on plugin uninstall by @kasparsd in https://github.com/WordPress/two-factor/pull/637

## New Contributors
* @szepeviktor made their first contribution in https://github.com/WordPress/two-factor/pull/617
* @mehul0810 made their first contribution in https://github.com/WordPress/two-factor/pull/616
* @thrijith made their first contribution in https://github.com/WordPress/two-factor/pull/623

**Full Changelog**: https://github.com/WordPress/two-factor/compare/0.9.1...master

### CODE REVIEW

**Comment by kasparsd** [comment]
@dd32 I see that in #625 we bumped both PHP and WP core requirements which would require a major release in my opinion.

Is there an practical need to bump those? Considering the important use-case for this plugin, I wonder if we can delay the requirement bumps until when actually needed them? 

Or did any of the session work actually need the WP bump?

@jeffpaul What are your thoughts on this?

**Comment by dd32** [comment]
> @dd32 I see that in #625 we bumped both PHP and WP core requirements which would require a major release in my opinion.

Personally, I disagree on that. Underlying requirements like this are background noise to 90% of people and does not signifiy anything major.
But happy for it to go out as 0.10.0 if you see fit, because I doubt you want to release as 1.0?

> Is there an practical need to bump those? Considering the important use-case for this plugin, I wonder if we can delay the requirement bumps until when actually needed them?

Considering what sites actually update plugins, this isn't really a concern to me, especially given the changes are not improving the sites security, and is more of a bugfix.

I did some digging for stat data for you, for 0.9.x of the plugin:
 - the PHP bump will affect 0.15% of users (1% If we include users of < 0.9)
 - the WP bump will affect 2.6% of 0.9.1 users (A singular site somewhere is using 0.9.1 + WP 6.2 according to the data, and nothing lower)
The overlap is that 100% of the old PHP users are running an older WP.

**Comment by jeffpaul** [comment]
@kasparsd there's still a decent amount of items in the [0.10.0 milestone](https://github.com/WordPress/two-factor/milestone/28), how much of that do you want to get pulled into this draft release and how can I help move those items along?

**Comment by jeffpaul** [comment]
@kasparsd any preference for the items in the 0.10.0 milestone that I can help get closer to done/merged to include in the release versus shipping what's currently merged in and punting the rest to the 0.11.0 milestone?

**Review by szepeviktor — APPROVED** [review]

**Comment by kasparsd** [comment]
@jeffpaul Personally I find the amount of items in the 0.10.0 milestone to be pretty overwhelming, and would suggest we do a release with whatever has been merged as it includes some major improvements.

I realize that this would require shifting the milestone items around -- is that a concern for you?

**Comment by kasparsd** [comment]
Considering that this release (and the included improvements) has been waiting around for a while, I'll go ahead and push it out. Monday gives us plenty of time to address any feedback.

**Comment by jeffpaul** [comment]
> I realize that this would require shifting the milestone items around -- is that a concern for you?

All updated here in GitHub, should be ok.

**Pull request merged**
